apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: 183631308419.dkr.ecr.us-east-1.amazonaws.com/paymentservice:1
        ports:
        - containerPort: 80

