apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: jenkins
spec:
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP